### ISSUE TITLE
Tiny black borders around tooltips

### ISSUE THREAD

**Issue by chuutatsu** [lah7/gtk3-classic#4]
When using GTK3-Mushrooms, everything worked perfectly except...
There are tiny black borders around the tooltips in all applications and panels. I am using Manjaro 17.1 (Mate desktop version 1.18).

**Comment by TomaszGasior** [comment]
Thanks for your post.

Please give me more information:
- GTK theme name,
- name of used window manager,
- screenshots.

Did you try to use default GTK theme, Adwaita?

**Comment by chuutatsu** [comment]
I am using Mate's default WM (Marco). The black borders looked like this. I used Materia theme.
![screenshot at 2018-01-22 03-47-04](https://user-images.githubusercontent.com/24815847/35198863-9cae0e3c-ff27-11e7-9c0f-28b92198fc8b.png)

The black borders also appeared when I used Numix and Mate's preinstalled themes (e.g. Menta, Blue Menta, BlackMate).

**Comment by TomaszGasior** [comment]
GTK3-mushrooms disables Client Side Decorations — themes are rendered as like when compositor is disabled. Some GTK3 themes are ugly if compositor is disabled, user should fix it manually.

Please add this to your `~/.config/gtk-3.0/gtk.css`:
```
tooltip {
	border-radius: 0;
	border-color: #eee;
}
```

**Comment by chuutatsu** [comment]
Sorry for very late reply. The fix above indeed worked perfectly.

However, I am still experiencing this. Right-clicking Mate panel still displayed the black border. Is there any way of fixing this?

![screenshot at 2018-02-15 17-29-50](https://user-images.githubusercontent.com/24815847/36252172-45101082-1276-11e8-89e8-395590237fb9.png)

**Comment by TomaszGasior** [comment]
Maybe you can try `menu, tooltip` instead `tooltip`.

**Comment by chuutatsu** [comment]
Yeah, it's working now! Thank you again!
